// app/layout.tsx (or wherever your RootLayout is located)
import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { CartProvider } from '../context/CartContext'
import { LocaleProvider } from '../context/LocalContext'

// ... rest of your imports and code
 // Adjust the path as necessary

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// Next.js App Router automatically provides `params` to the root layout if it's a dynamic route.
// For internationalization (i18n), your folder structure would typically be:
// app/[locale]/layout.tsx
// This allows `params.locale` to be available here.
export default function RootLayout({
  children,
  params // Add params to the RootLayout props
}: {
  children: React.ReactNode;
  // Define the type for params, expecting a locale string
  params: { locale: string };
}) {
  const { locale } = params; // Extract locale directly from params

  return (
    <html lang={locale}> {/* Optionally set html lang attribute */}
      {/* Wrap both CartProvider and the body with LocaleProvider */}
      <LocaleProvider locale={locale}>
        <CartProvider>
          <body className={inter.className}>{children}</body>
        </CartProvider>
      </LocaleProvider>
    </html>
  )
}